fix for SC2145

diff --git a/files/homes.desktop/bin/mastvoldown b/files/homes.desktop/bin/mastvoldown
--- a/files/homes.desktop/bin/mastvoldown
+++ b/files/homes.desktop/bin/mastvoldown
@@ -22,7 +22,7 @@ detect_vol() {
 
 usageerror() {
     if [ $# != 0 ] ; then
-        echo "Usage error: $@" 1>&2
+        echo "Usage error:" "$@" 1>&2
     fi
     echo "Usage: $0 [--small|-s] [--large|-l]+" 1>&2
     exit 1
