wait-and-query-rerun, x: lots of extra flags
partially ported to ksh before realising I didn't need the tradeoff
between speed and bash niceness

A lot of output prettied-up:
  /home/$user -> ~user in a lot of output
  /usr/local/bin, $HOME/bin suppressed from a lot of output
  Fix a bunch of quoting
  enforce_title_length for window title

make flags between these and verboserun, colorizecommand etc more
consistent

add --title override

a bit of change of behaviour between --shell, wait-and-query-rerun, verboserun

diff --git a/files/homes/bin/wait-and-query-rerun b/files/homes/bin/wait-and-query-rerun
--- a/files/homes/bin/wait-and-query-rerun
+++ b/files/homes/bin/wait-and-query-rerun
@@ -1,35 +1,100 @@
 #!/bin/bash
 
-function failure_tone() {
+# Internal tool assumed to be called from within the xterm called by
+# `x`
+
+failure_tone() {
     beepfreq -f 500 -d 0.1 -v 0.02 > /dev/null &
 }
 
-function winname() {
+replace_binpath() {
+    sed "s!/usr/local/s?bin/!!; s!$HOME/bin/!!"
+}
+
+replace_home_tilde() {
+    sed -E "s!^$HOME(/|$)!~\1!"
+}
+
+winname() {
     echo -ne '\033]2;'"$1"'\007' 1>&2
 }
 
-function calculate_text_display() {
+calculate_text_display() {
+    local cmd="$1"
+    shift
+
+    # local cmd_abbr="$(                echo "$cmd" | replace_binpath | replace_home_tilde )"
+    local cmd_abbr_escaped="$( printf "%q" "$cmd" | replace_binpath | replace_home_tilde )"
+
+    printf '%s' "$cmd_abbr_escaped"
+
     for i in "$@" ; do
         printf ' %q' "$i"
     done
 }
 
-function calculate_window_display() {
-    printf '`%s' "$1"
-    shift
-    for i in "$@" ; do
-        printf ' %q' "$i"
-    done
-    printf '` (%q)' "$dir"
+calculate_window_display() {
+    title_columns=$(( $( tput cols )*11/10))
+
+    (
+        cmd="$1"
+        shift
+
+        cmd_abbr="$(                echo "$cmd" | replace_binpath | replace_home_tilde )"
+        # cmd_abbr_escaped="$( printf "%q" "$cmd" | replace_binpath | replace_home_tilde )"
+
+        printf '`%s' "$cmd_abbr"
+
+        for i in "$@" ; do
+            # printf ' %q' "$i"
+            printf ' %s' "$i"
+        done
+        printf '` (%s)' "$dir_abbr"
+    ) | (
+        read -r title
+        chomp --middle ... "$title_columns" "$title"
+    )
 }
 
-verbose=false
-if [ "$1" = --verbose ] ; then
-    shift
-    verbose=true
+usage() {
+    echo "Error in internal tool called by x" 1>&2
+    exit 1
+}
+
+if [ "$#" = 0 ] ; then
+    usage
 fi
 
+shell=
+verbose=false
+clean_exit_timeout=
+while [[ "$1" == -* ]] ; do
+    case "$1" in
+        --shell)
+            shell="--shell"
+            shift
+            ;;
+        --no-verbose|--verbose=false)
+            verbose=false
+            shift
+            ;;
+        --verbose|--verbose=true)
+            verbose=true
+            shift
+            ;;
+        -t)
+            clean_exit_timeout="-t $2"
+            shift ; shift
+            ;;
+        --*)
+            usage
+            ;;
+    esac
+done
+
 dir="$(pwd)"
+dir_abbr="$(                echo "$dir" | replace_home_tilde )"
+dir_abbr_escaped="$( printf "%q" "$dir" | replace_home_tilde )"
 PTS=`readlink /dev/fd/0` ; PTS="${PTS#/dev/}"
 
 while : ; do
@@ -42,11 +107,15 @@ while : ; do
     echo "$( date ): running"
     colorize -n bright cyan "$text_title"
     echo -n " in "
-    colorize bright magenta "$( printf "%q\n" "$dir" )"
+    colorize bright magenta "$dir_abbr_escaped"
     if $verbose ; then
-        verboserun "$@"
+        verboserun $shell "$@"
     else
-        "$@"
+        if [ -n "$shell" ] ; then
+            sh -c "$@"
+        else
+            "$@"
+        fi
     fi
     exit=$?
     while read -t 0.1 purge ; do
@@ -57,16 +126,16 @@ while : ; do
         echo "$( date ): finished"
         colorize -n bright cyan "$text_title"
         echo -n " in "
-        colorize bright magenta "$( printf "%q\n" "$dir" )"
-        echo "$( colorize bright green $( date ) ): $( colorize bright green Success 0 ): Press enter to exit..."
-        read
+        colorize bright magenta "$dir_abbr_escaped"
+        echo "$( colorize bright green $( date ) ): $( colorize bright green Success 0 ): Press enter to exit${clean_exit_timeout:+ (Will exit in $clean_exit_timeout otherwise)}..."
+        read $clean_exit_timeout
         exit
     else
-        echo "$( date ): $dir:$text_title failed..."
+        #echo "$( date ): $dir:$text_title failed..."
         failure_tone
         winname "x ($PTS): failed: $window_title"
-        echo "$( colorize bright green $( date ) ): $( colorize bright red Failed $exit ): $( colorize bright magenta $PWD )"
-        echo "$( colorize bright yellow "$( printf " %q" "$@")" )"
+        echo "$( colorize bright green $( date ) ): $( colorize bright red Failed $exit ): $( colorize bright magenta "$dir_abbr_escaped" )"
+        echo "$( colorize bright yellow "$text_title" )"
         echo "Type 'OK' or ctrl-D to exit, or anything else to retry"
         read a || exit 1
         if [ "$a" = OK ] ; then
diff --git a/files/homes/bin/x b/files/homes/bin/x
--- a/files/homes/bin/x
+++ b/files/homes/bin/x
@@ -24,13 +24,23 @@ retry() {
     done
 }
 
+enforce_title_length() {
+    local title="$*"
+
+    title_limit=120 # we don't know the size the xterm will be, yet
+
+    chomp --middle ... "$title_limit" "$title"
+}
+
 eval="verboserun"
 noshell=true
-verbose=true
+verbose=false
+retry=retry
+wait_timeout=
 while [[ "$1" == --* ]] ; do
     case "$1" in
         --help)
-            cat <<EOF
+            cat 1>&2 <<EOF
 Usage: x [--help] [--title <title>] [--no-retry] [--wait[=clean-exit-timeout]] [--no-verbose|--verbose[=<true|false>]] [--no-eval] [--shell] [--] [-other-xterm-flags...] [--] <prog> [<args>]"
 Runs PROG within an xterm, setting window title and potentially retrying as necessary
 
@@ -43,18 +53,34 @@ Runs PROG within an xterm, setting window title and potentially retrying as nece
   --no-verbose            Be less verbose than default
   --no-eval               Just run the command within bash with nothing else interpreting the
                            command status, and be very quiet about invocation
-  --shell                 Run the command within a shell context as well as potentially under the control of our status checker
+  --shell                 Run the command within a shell context as well as potentially under the control
+                           of our status checker
   --help                  Display this help and exit
 EOF
             exit 1
             ;;
-        --wait)
-            shift
-            eval='wait-and-query-rerun'
+        --title)
+            title="$2"
+            shift 2
             ;;
-        --noverbose)
+        --wait*)
+            if [[ "$1" == --wait=* ]] ; then
+                wait_timeout="${1#--wait=}"
+            fi
             shift
+            eval="wait-and-query-rerun${wait_timeout:+ -t $wait_timeout}"
+            ;;
+        --no-retry)
+            shift
+            retry=
+            ;;
+        --no-verbose|--verbose=false)
             verbose=false
+            shift
+            ;;
+        --verbose|--verbose=true)
+            verbose=true
+            shift
             ;;
         --no-eval)
             shift
@@ -70,12 +96,21 @@ EOF
     esac
 done
 
-if [ $eval == wait-and-query-rerun ] ; then
-    if $verbose ; then
-        eval="$eval --verbose"
-    fi
+
+if [ "$eval" == 'wait-and-query-rerun' ] ; then
+    eval="$eval --verbose=$verbose"
     if ! $noshell ; then
         eval="$eval --shell"
+    fi
+elif [ "$eval" = verboserun ] ; then
+    eval="$eval --verbose=$verbose"
+    if ! $noshell ; then
+        eval="$eval --shell"
+    fi
+else  # no eval, but they might still be asking for a shell (kinda the
+      # same thing, eh?)
+    if ! $noshell ; then
+        eval='bash -c'
     fi
 fi
 
@@ -104,8 +139,20 @@ while [ $# != 0 ] ; do
     shift
 done
 
-if [ "${#cmds[@]}" != 0 ] ; then
-    retry xterm "${args[@]}" -T "x: $PWD ${cmds[*]}" -e bash $eval "${cmds[@]}" # ${cmds[*]}
-else
-    retry xterm "${args[@]}"
-fi &
+(
+    if [ "${#cmds[@]}" = 0 ] ; then
+        cmds+=("bash")
+    fi
+    # we don't know the tty yet, nor the size of the window, so
+    # there's no useful metadata to display at the front of the window
+    # title to identify this window yet
+    title="${title-$( enforce_title_length x: "$PWD" "${cmds[@]}" )}"
+    $retry xterm "${args[@]}" -T "$title" -e $eval "${cmds[@]}" &
+    sleep 0.3  # if we exit too soon, and in turn our caller (eg
+               # xterm, ssh) exits, then our child might not even get
+               # a chance to spawn.  This is awful, I wish there were
+               # a better way to get confirmation that the xterm had
+               # actually opened (plus, the retry loop could wait in
+               # the foreground until the xterm succeeds in
+               # opening)...
+)
