colorizecommand,verboserun: forgot to exit with the right exit code!

diff --git a/files/homes/bin/x b/files/homes/bin/x
--- a/files/homes/bin/x
+++ b/files/homes/bin/x
@@ -9,7 +9,7 @@
 retry() {
     "$@" && return
     while : ; do
-          echo "$(date): xterm failed with exit-code: $?.  Retrying in a minute..."
+          echo "$(date): xterm failed with exit-code: $?.  Retrying in a minute (in the background)..."
           sleep 60
           verboserun "$@" && return
     done
