not quite sure what the eval was for in the debug message, but it ended up not doing the needful anyway

diff --git a/roles/pve_server/files/monitoring/check_ceph_overall b/roles/pve_server/files/monitoring/check_ceph_overall
--- a/roles/pve_server/files/monitoring/check_ceph_overall
+++ b/roles/pve_server/files/monitoring/check_ceph_overall
@@ -7,10 +7,10 @@ fail=false
 failed_tests=
 
 function fail() {
-    cmd_failed=$( eval echo "$BASH_COMMAND" )
-    echo " * -> Failed: $cmd_failed"
+    code=$? ; CMD="$BASH_COMMAND"
+    echo " * -> Failed($code): $CMD"
 
-    failed_tests="$failed_tests$cmd_failed ; "
+    failed_tests="$failed_tests$CMD ; "
     fail=true
 }
 
@@ -46,7 +46,7 @@ done
 ./check_ceph_osd_df -W 90 -C 95
 #./check_ceph_rgw  # rados gateway to S3
 
-if "$fail" ; then
+if $fail ; then
     echo Failed tests: $failed_tests
     exit 1
 fi
