github-cicd: shellcheck: fix a few SC2290, SC2145, SC2148

diff --git a/files/tree/usr/local/bin/colorizecommand b/files/tree/usr/local/bin/colorizecommand
--- a/files/tree/usr/local/bin/colorizecommand
+++ b/files/tree/usr/local/bin/colorizecommand
@@ -71,7 +71,7 @@ usage() {
 
 usageerror() {
     if [ "$#" != 0 ] ; then
-        echo "Usage error: $@" 1>&2
+        echo "Usage error:" "$@" 1>&2
         echo "Usage was $ARGS" 1>&2
     fi
     usage 1
